#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by GradleWrapperBootstrapper.
#
#   You can find more information about Gradle Wrapper at:
#   https://docs.gradle.org/8.2/userguide/gradle_wrapper.html
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for da * suffixes as Gradle does not
#  da * as filenames and "shell wildcard expansion" is disabled by "set -f".
IFS="$(printf '\n ')" ; set -f  ; IFS="$(printf ' \n')" ; set +f

# shellcheck disable=SC203313
APP_NAME=$0
APP_BASE_NAME=$( basename "$APP_NAME" )
APP_HOME=$( cd "${APP_HOME:-./}">/dev/null && echo "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# A COPY OF THE Apache LICENSE, VERSION 2.0 IS INCLUDED WITH THIS SOFTWARE.
# THE LICENSE CAN BE OBTAINED AT https://www.apache.org/licenses/LICENSE-2.0.
#
# *****************************************************************************
# 
# If you want to enable shell debugging, add -x to the #!/bin/sh line.
#
##############################################################################

# Increase the maximum file descriptors if we can
if [ "$MAX_FD" != "maximum" ] ; then
    ulimit -n "$MAX_FD" 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo "Could not set maximum file descriptors for $APP_BASE_NAME"
    fi
else
    case "$( ulimit -n 2>/dev/null )" in
        *unlimited*)
            # Do nothing
        ;;
        *)
            # Try to increase the maximum file descriptors
            ulimit -n 1024 2>/dev/null
        ;;
    esac
fi

# For Darwin, add options to specify how the application will be treated in Dock
if [ "$( uname )" = "Darwin" ]; then
    DEFAULT_JWM_OPTS="-XstartOnFirstThread"
else
    DEFAULT_JWM_OPTS=""
fi

# Collect all arguments for the java command, following the shell quoting and expansion rules
# We need to handle quotes and backslashes specially
eval set -- $DEFAULT_JWM_OPTS "$@"

# Escape application args
escape_args=""
for arg do
    case $arg in
        *' D'*)
            # D on its own needs to be escaped
            arg="$_ESCAPE_D_AS_OPT"
        ;;
    esac
    escape_args="$escape_args \"$arg\""
done

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Find java and check its version
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ !  -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation, or install a JDK that includes 'java'."
fi

# Increase the maximum file descriptors if we can
if [ "$MAX_FD" != "maximum" ] ; then
    ulimit -n "$MAX_FD" 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo "Could not set maximum file descriptors for $APP_BASE_NAME"
    fi
else
    case "$( ulimit -n 2>/dev/null )" in
        *unlimited*)
            # Do nothing
        ;;
        *)
            # Try to increase the maximum file descriptors
            ulimit -n 1024 2>/dev/null
        ;;
    esac
fi

# Split up the JVM options
JVM_OPTS="$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS"
JVM_OPTS=$( echo "$JVM_OPTS" | xargs )
eval set -- $JVM_OPTS

# Escape application args
escape_args=""
for arg do
    case $arg in
        *' D'*)
            # D on its own needs to be escaped
            arg="$_ESCAPE_D_AS_OPT"
        ;;
    esac
    escape_args="$escape_args \"$arg\""
done

# Execute Gradle
exec "$JAVACMD" "$@" $escape_args -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
