name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: r0adkll/build-android@v1
        with:
          project-path: ./
          output-pattern: '**/*.apk'
          cache: gradle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: "**/*.apk"
          if-no-files-found: error
